# Generated by Django 4.2.11 on 2024-05-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Category id')),
                ('name', models.CharField(max_length=20, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='User id')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('img', models.ImageField(default='user/default.jpg', upload_to='user', verbose_name='User Avatar')),
                ('sex', models.CharField(default='Male', max_length=10, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Movie id')),
                ('name', models.CharField(max_length=100, verbose_name='Movie Name')),
                ('desc', models.TextField(verbose_name='Movie Description')),
                ('score', models.FloatField(default=0, verbose_name='Movie Rating')),
                ('img', models.ImageField(upload_to='movie', verbose_name='Movie Picture')),
                ('release_time', models.DateField(verbose_name='Release Time')),
                ('duration', models.IntegerField(verbose_name='Length')),
                ('director', models.CharField(max_length=20, verbose_name='Director')),
                ('actor', models.CharField(max_length=100, verbose_name='Actor')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('area', models.CharField(default='China', max_length=20, verbose_name='Region')),
                ('language', models.CharField(default='Chinese', max_length=20, verbose_name='Language')),
                ('status', models.CharField(default='Released', max_length=20, verbose_name='Status')),
                ('url', models.CharField(default='https://www.baidu.com', max_length=100, verbose_name='Play Address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.category', verbose_name='Category')),
            ],
        ),
    ]
