# Generated by Django 4.2.11 on 2024-05-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Movie Category', 'verbose_name_plural': 'Movie Category'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie Information', 'verbose_name_plural': 'Movie Information'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='user/default.jpg', upload_to='user/', verbose_name='User Avatar'),
        ),
    ]
