# Generated by Django 5.1.5 on 2025-01-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_category_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('Schedule Task', 'Schedule Task'), ('Check Progress', 'Check Progress')], max_length=50)),
                ('input_command', models.TextField()),
                ('associated_task_meeting_id', models.IntegerField(blank=True, null=True)),
                ('response_type', models.CharField(choices=[('Chat', 'Chat'), ('Action', 'Action')], max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('Email', 'Email'), ('Notification', 'Notification'), ('Dashboard', 'Dashboard')], max_length=50)),
                ('associated_task_meeting_id', models.IntegerField()),
                ('reminder_date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Pending', 'Pending')], max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('id',), 'verbose_name': 'Movie Info', 'verbose_name_plural': 'Movie Info'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.CharField(max_length=100, verbose_name='Actors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='area',
            field=models.CharField(default='Singapore', max_length=20, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.category', verbose_name='Movie Category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(verbose_name='Movie Length'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=20, verbose_name='Language'),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_block_start', models.TimeField()),
                ('time_block_end', models.TimeField()),
                ('associated_task_meeting_id', models.IntegerField()),
                ('conflict_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='webapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('attachments', models.TextField(blank=True, null=True)),
                ('template_id', models.IntegerField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('sent_date_time', models.DateTimeField()),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to='webapp.user')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='webapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=100)),
                ('organizer_name', models.CharField(max_length=50)),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('meeting_notes', models.TextField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('participants', models.ManyToManyField(related_name='meetings', to='webapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Personal', 'Personal'), ('Project', 'Project')], max_length=50)),
                ('generated_date_time', models.DateTimeField()),
                ('time_range_start', models.DateTimeField()),
                ('time_range_end', models.DateTimeField()),
                ('indicators_tracked', models.TextField()),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='webapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('task_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=15)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('associated_event_id', models.IntegerField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('task_summary', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='webapp.user')),
            ],
        ),
    ]
